### PR TITLE
rewrite some functions in point-free style

### PR DESCRIPTION
**Pull request by subttle**
Per discussion in https://github.com/emilypi/smash/issues/22. Additionally I thought `swapWedge` was a good candidate so I added that even though I hadn't explicitly listed it prior in the issue. Please let me know if you would like me to make any edits. Thanks!

### CODE REVIEW

**Comment by subttle** [comment]
Hmm the build seems to be failing with:
```
src/Data/Can/Lens.hs:147:10: error:
    Not in scope: type constructor or class ‘Swapped’
    A data constructor of that name is in scope; did you mean DataKinds?
    Perhaps you meant ‘Wrapped’ (imported from Control.Lens)
    |
147 | instance Swapped Can where
    |          ^^^^^^^
cabal: Failed to build smash-lens-0.1.0.1.
```
```
src/Data/Can/Lens.hs:147:10: error:
    Not in scope: type constructor or class ‘Swapped’
    A data constructor of that name is in scope; did you mean DataKinds?
    Perhaps you meant ‘Wrapped’ (imported from Control.Lens)
    |
147 | instance Swapped Can where
    |          ^^^^^^^
cabal: Failed to build documentation for smash-lens-0.1.0.1.
```
I didn't touch any of the Lens code so it would take me some time to figure out. Hopefully I'll have some time to look into it soon. Sorry for the inconvenience.

**Comment by emilypi** [comment]
Yeah, the lens bounds need to be tightened. I have a PR out for that.

**Comment by subttle** [comment]
Okay, great! No rush, thanks for the update!

**Comment by emilypi** [comment]
@subttle alright, other PR is merged, and your CI should be good to go if you merge that PR into this branch.

**Review by emilypi — APPROVED** [review]

**Pull request merged**
